//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceUaa
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public int idClientes { get; set; }
        public int idTipoCliente { get; set; }
        public int idCiudad { get; set; }
        public string cli_ruc { get; set; }
        public string cli_razonsocial { get; set; }
        public string cli_direccion { get; set; }
        public string cli_email { get; set; }
        public string cli_telefono { get; set; }
        public string usuarioId { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Ciudad Ciudad { get; set; }
        public virtual TipoCliente TipoCliente { get; set; }
        public virtual Pedido Pedido { get; set; }
    }
}
