//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceUaa
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entrega
    {
        public int id_entrega { get; set; }
        public int id_pedido { get; set; }
        public string chofer { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual Pedido Pedido { get; set; }
    }
}
