//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceUaa
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoDetalle
    {
        public int idPedidoDetalle { get; set; }
        public int idProducto { get; set; }
        public int idPedidoCabecera { get; set; }
        public int pedet_precio { get; set; }
        public int pedet_montototal { get; set; }
        public int pedet_cantidad { get; set; }
    
        public virtual Pedido Pedido { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
